name: Issue Reply

on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Usage
        if: github.event.label.name == 'Usage' || github.event.label.name == 'Question'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Vue Accessible. So, please don't ask usage questions. You can join the community to ask questions:
            - [N/A](#)

            你好 @${{ github.event.issue.user.login }}，Vue Accessible Issue 板块是用于 bug 反馈与需求讨论的地方，请勿询问如何使用的问题。你可以加入社区进行提问：
            - [暂无](#)
