name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - main
      - feat/v1
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'ROYIANS/vue-accessible'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ROYIANS/vue-accessible.git'
          destination-repo: 'git@gitee.com:ROYIANS/vue-accessible.git'